### ISSUE TITLE
Thiếu tháng 7 âm lịch

### ISSUE THREAD

**Issue by truongbber** [ExlLab/lich_am#6]
bác fix sensor đi, thiếu toàn bộ tháng 7 âm lịch

**Comment by ExlLab** [comment]
Thiếu làm sao được.
Năm 2025 có 2 tháng 6 (Tháng 6 nhuận).

**Comment by truongbber** [comment]
> Thiếu làm sao được. Năm 2025 có 2 tháng 6 (Tháng 6 nhuận).

mình tìm tháng 7 trong file senso ko có mà, có 2 tháng 6 thì cũng vẫn phải có tháng 7 chứ

**Comment by ExlLab** [comment]
Dữ liệu 12 tháng bạn nhé.

**Comment by ExlLab** [comment]
Bạn muốn có tháng 7 âm lịch thì gửi yêu cầu vào email này nhé (exlab247@gmail.com)
